# We don't need sudo as such, but setting sudo: required allows us to run on
# the faster machines which means that the builds complete much faster (in
# about half the time). For comparison, here are two builds on the two
# different machines:
# - With `sudo: false`: https://travis-ci.org/opbeat/opbeat-node/builds/252301998
# - With `sudo: required`: https://travis-ci.org/opbeat/opbeat-node/builds/252302576
sudo: required

language: node_js

node_js:
  - '10'
  - '9'
  - '8'

env:
  - FOO=1
  - FOO=2
  - FOO=3
  - FOO=4
  - FOO=5
  - FOO=6
  - FOO=7
  - FOO=9
  - FOO=10
  - FOO=11
  - FOO=12
  - FOO=13
  - FOO=14
  - FOO=15
  - FOO=16
  - FOO=17
  - FOO=18
  - FOO=19
  - FOO=20

script: echo "hello world"
